#! /bin/bash

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "Not in a git repository!"
  exit 1
fi

git fetch -p && git branch -vv | grep ': gone]' | awk '{print $1}' | xargs git branch -D 2>/dev/null || echo 'No dead branches found to delete.'

